name: Makefile CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: make

      - name: Run check
        run: make check
